server {
  listen       5173;
  location = /search/health/check {
    add_header Content-Type "text/plain";
    return 200 "ok";
  }

  location ^~ /search {
    index  index.html index.htm;
    alias /html;
    try_files $uri $uri/ /index.html =404;
  }
}